"""add created_at

Revision ID: 68186bacdc5a
Revises: 73f5227014be
Create Date: 2026-05-11 21:39:40.177726

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68186bacdc5a"
down_revision: Union[str, Sequence[str], None] = "73f5227014be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.execute("Update log set created_at = NOW() ")
    op.alter_column("log", "created_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log", "created_at")
    # ### end Alembic commands ###
