"""add logger to log

Revision ID: 73f5227014be
Revises: 9a44cce26de8
Create Date: 2026-05-10 04:10:28.901881

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73f5227014be"
down_revision: Union[str, Sequence[str], None] = "9a44cce26de8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "log", sa.Column("logger", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.execute("Update log set logger=''")
    op.alter_column("log", "logger", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log", "logger")
    # ### end Alembic commands ###
